# command to create the pod is --> kubectl create -f <file_name>
apiVersion: v1
kind: Pod
metadata:
     name: nginx-pod
     labels: 
        tier: web
        app: middleware
spec:
  containers:
      - name: nginxc
        image: nginx
