# from remote
# command to create the pod is --> kubectl create -f <file_name>
# comment to create or update the resource --> kubectl apply -f <file-name>wq!
apiVersion: v1
kind: Pod
metadata:
     name: nginx-pod
     labels: 
        tier: web
        app: middleware
spec:
  containers:
      - name: nginxc
        image: nginx
